<a href="https://colab.research.google.com/github/Eizer-GH/PDS/blob/main/Ex2_B4_55_PrasadV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

```
NAME - Prasad Sanjay Vangujare
CLASS - SY.B [AIDS]
ROLL NO.- B55
SUBJECT - EX_2 PDS
```

```
Aim - Data Ingestion and Cleaning: Acquire data and prepare it
for analysis.
```

```

Theory :

1. What is data ingestion and why is it important in data science?
   Which Python  library is commonly used for data ingestion
   and cleaning?

Ans:
Data ingestion is the process of collecting and importing data from
different sources such as CSV files, databases, APIs, or Excel files
into a system for further processing and analysis.

Data ingestion is important in data science because:
It allows data scientists to gather data from multiple sources.
It prepares raw data for analysis and machine learning.
It ensures data is available in a structured format.
Without proper ingestion, analysis cannot begin.

The most commonly used Python library for data ingestion and
cleaning is Pandas.

Other useful libraries include:
NumPy – for numerical operations
OpenPyXL – for Excel files
CSV module – for reading CSV files


2. Why is data cleaning necessary before performing analysis or
   machine learning?

Ans:
Data cleaning is necessary because real-world data is often
incomplete, inconsistent, or incorrect.

Data cleaning helps to:
Remove missing values
Fix incorrect or duplicate data
Standardize formats
Improve accuracy of results
Enhance performance of machine learning models

If data is not cleaned properly, it can lead to:
Incorrect analysis results
Poor model performance
Misleading conclusions

Clean data acts like polished glass — the clearer it is, the clearer
the insights you see.


3. How do you load a CSV file into a Pandas DataFrame?

Ans:
A CSV file can be loaded into a Pandas DataFrame using the read_csv()
function.

Syntax:

import pandas as pd
df = pd.read_csv("filename.csv")

This command reads the CSV file and stores the data into a DataFrame
named data, which can then be used for analysis.


4. What is the difference between head() and tail() functions
   in Pandas?

Ans:
Both head() and tail() functions are used to view rows of a dataset.

| Function   | Description                                |
| ---------- | ------------------------------------------ |
|   head()   | Displays the first few rows of the dataset |
|   tail()   | Displays the last few rows of the dataset  |

Default Behavior:

head() shows first 5 rows
tail() shows last 5 rows

Example:
df.head(10)
df.tail(10)

These functions are useful for quickly previewing data without
scrolling through the entire dataset.


5. How can you identify missing values in a dataset?

Ans:
Missing values in a dataset can be identified using the isnull()
or isna() functions in Pandas.

Methods to identify missing values:

1] Check missing values in dataset
   df.isnull()

2] Count missing values in each column
   df.isnull().sum()

3] Check if any missing value exists
   df.isnull().any()

These functions help detect incomplete data so that it can be
cleaned or filled before performing analysis.


```

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("/content/employee_data.csv")  #Loads CSV file

In [ ]:
df.head()

,Employee_ID,Name,Age,Gender,Department,Join_Date,Salary,Experience,Performance_Rating,Bonus,Work_Hours_Per_Week
0,101,Alice,50,Female,Marketing,2009-01-18,62606.0,13.0,2.0,9488.0,44.0
1,102,Bob,36,Female,Marketing,2012-01-01,41534.0,1.0,1.0,5206.0,40.0
2,103,Charlie,29,Female,IT,2007-02-15,NaN,9.0,4.0,10134.0,33.0
3,104,David,42,Male,Marketing,2015-12-29,31016.0,7.0,1.0,10977.0,42.0
4,105,Eve,40,Female,IT,2005-02-04,119789.0,9.0,4.0,12721.0,36.0

In [ ]:
# Check missing values
df.isnull().sum()

Employee_ID            0
Name                   0
Age                    0
Gender                 0
Department             0
Join_Date              0
Salary                 1
Experience             1
Performance_Rating     1
Bonus                  1
Work_Hours_Per_Week    1
dtype: int64

In [ ]:
# Replace missing values with zero
df_filled = df.fillna(0)
df_filled.head(20)

,Employee_ID,Name,Age,Gender,Department,Join_Date,Salary,Experience,Performance_Rating,Bonus,Work_Hours_Per_Week
0,101,Alice,50,Female,Marketing,2009-01-18,62606.0,13.0,2.0,9488.0,44.0
1,102,Bob,36,Female,Marketing,2012-01-01,41534.0,1.0,1.0,5206.0,40.0
2,103,Charlie,29,Female,IT,2007-02-15,0.0,9.0,4.0,10134.0,33.0
3,104,David,42,Male,Marketing,2015-12-29,31016.0,7.0,1.0,10977.0,42.0
4,105,Eve,40,Female,IT,2005-02-04,119789.0,9.0,4.0,12721.0,36.0
5,106,Frank,44,Male,Marketing,2013-08-19,85591.0,0.0,2.0,12035.0,48.0
6,107,Grace,32,Male,Marketing,2010-05-10,119812.0,1.0,1.0,6484.0,31.0
7,108,Hank,32,Male,IT,2009-05-05,53247.0,12.0,5.0,12858.0,39.0
8,109,Ivy,45,Male,IT,2015-10-19,54300.0,8.0,0.0,5863.0,42.0
9,110,Jack,57,Male,Marketing,2013-06-01,104065.0,8.0,4.0,7790.0,35.0
10,111,Kate,45,Female,HR,2007-10-19,112798.0,11.0,3.0,12408.0,41.0
11,112,Leo,24,Female,IT,2014-06-24,39268.0,3.0,3.0,13755.0,41.0
12,113,Mona,43,Female,HR,2012-02-27,116807.0,1.0,1.0,10116.0,49.0
13,114,Nina,23,Female,HR,2019-04-23,42185.0,8.0,3.0,17383.0,40.0
14,115,Oscar,45,Female,HR,2015-07-11,93704.0,3.0,5.0,0.0,36.0
15,116,Paul,51,Male,IT,2009-02-09,116779.0,3.0,3.0,6757.0,30.0
16,117,Quinn,59,Female,HR,2018-02-20,69099.0,1.0,1.0,19820.0,30.0
17,118,Rose,23,Female,IT,2005-06-11,38571.0,11.0,5.0,12574.0,49.0
18,119,Steve,42,Male,HR,2016-10-07,68044.0,5.0,2.0,11374.0,0.0
19,120,Tina,54,Female,Marketing,2010-06-05,81214.0,10.0,3.0,11892.0,38.0

In [ ]:
# Print column names vertically in lowercase
df.columns = df.columns.str.lower()
for col in df.columns:
    print(col)

employee_id
name
age
gender
department
join_date
salary
experience
performance_rating
bonus
work_hours_per_week

In [ ]:
df.shape

(20, 11)

In [ ]:
df = df.drop_duplicates()

In [ ]:
# Fill numeric missing values using mean
df.fillna(df.mean(numeric_only=True), inplace=True)
df.isnull().sum()
df.head(20)

,employee_id,name,age,gender,department,join_date,salary,experience,performance_rating,bonus,work_hours_per_week
0,101,Alice,50,Female,Marketing,2009-01-18,62606.000000,13.000000,2.000000,9488.000000,44.000000
1,102,Bob,36,Female,Marketing,2012-01-01,41534.000000,1.000000,1.000000,5206.000000,40.000000
2,103,Charlie,29,Female,IT,2007-02-15,76338.368421,9.000000,4.000000,10134.000000,33.000000
3,104,David,42,Male,Marketing,2015-12-29,31016.000000,7.000000,1.000000,10977.000000,42.000000
4,105,Eve,40,Female,IT,2005-02-04,119789.000000,9.000000,4.000000,12721.000000,36.000000
5,106,Frank,44,Male,Marketing,2013-08-19,85591.000000,6.526316,2.000000,12035.000000,48.000000
6,107,Grace,32,Male,Marketing,2010-05-10,119812.000000,1.000000,1.000000,6484.000000,31.000000
7,108,Hank,32,Male,IT,2009-05-05,53247.000000,12.000000,5.000000,12858.000000,39.000000
8,109,Ivy,45,Male,IT,2015-10-19,54300.000000,8.000000,2.789474,5863.000000,42.000000
9,110,Jack,57,Male,Marketing,2013-06-01,104065.000000,8.000000,4.000000,7790.000000,35.000000
10,111,Kate,45,Female,HR,2007-10-19,112798.000000,11.000000,3.000000,12408.000000,41.000000
11,112,Leo,24,Female,IT,2014-06-24,39268.000000,3.000000,3.000000,13755.000000,41.000000
12,113,Mona,43,Female,HR,2012-02-27,116807.000000,1.000000,1.000000,10116.000000,49.000000
13,114,Nina,23,Female,HR,2019-04-23,42185.000000,8.000000,3.000000,17383.000000,40.000000
14,115,Oscar,45,Female,HR,2015-07-11,93704.000000,3.000000,5.000000,11033.421053,36.000000
15,116,Paul,51,Male,IT,2009-02-09,116779.000000,3.000000,3.000000,6757.000000,30.000000
16,117,Quinn,59,Female,HR,2018-02-20,69099.000000,1.000000,1.000000,19820.000000,30.000000
17,118,Rose,23,Female,IT,2005-06-11,38571.000000,11.000000,5.000000,12574.000000,49.000000
18,119,Steve,42,Male,HR,2016-10-07,68044.000000,5.000000,2.000000,11374.000000,39.157895
19,120,Tina,54,Female,Marketing,2010-06-05,81214.000000,10.000000,3.000000,11892.000000,38.000000

In [ ]:
# Convert selected columns from float to int
df['age'] = df['age'].astype(int)
df['salary'] = df['salary'].astype(int)
df['experience'] = df['experience'].astype(int)
df['performance_rating'] = df['performance_rating'].astype(int)
df['bonus'] = df['bonus'].astype(int)
df['work_hours_per_week'] = df['work_hours_per_week'].astype(int)

df.head()

,employee_id,name,age,gender,department,join_date,salary,experience,performance_rating,bonus,work_hours_per_week
0,101,Alice,50,Female,Marketing,2009-01-18,62606,13,2,9488,44
1,102,Bob,36,Female,Marketing,2012-01-01,41534,1,1,5206,40
2,103,Charlie,29,Female,IT,2007-02-15,76338,9,4,10134,33
3,104,David,42,Male,Marketing,2015-12-29,31016,7,1,10977,42
4,105,Eve,40,Female,IT,2005-02-04,119789,9,4,12721,36

In [ ]:
# Filter employees with salary > 100000
filtered_df = df[df['salary'] > 100000]
filtered_df.iloc[:, :7].head()

    employee_id   name  age  gender department   join_date  salary
4           105    Eve   40  Female         IT  2005-02-04  119789
6           107  Grace   32    Male  Marketing  2010-05-10  119812
9           110   Jack   57    Male  Marketing  2013-06-01  104065
10          111   Kate   45  Female         HR  2007-10-19  112798
12          113   Mona   43  Female         HR  2012-02-27  116807

In [ ]:
# Save cleaned dataset
df.to_csv("cleaned_employee_data.csv", index=False)

```
Conclusion:

The data ingestion and cleaning process was successfully performed using the Pandas library in Python.
The dataset was loaded into a DataFrame, and initial inspection was carried out by displaying the first
few rows and checking the dataset shape. Missing values were identified and handled using appropriate
methods such as replacing values with zero and filling numeric values using the mean.

Column names were standardized by converting them to lowercase, duplicate records were removed, and
selected data types were modified to ensure proper formatting. Filtering operations were also applied
to extract specific records based on given conditions. Finally, the cleaned dataset was saved as a new
CSV file for further analysis.

Thus, this practical demonstrated how raw data can be effectively ingested, cleaned, and prepared for
analysis using Python, making the dataset more accurate, consistent, and ready for future data analysis
or machine learning tasks.
```