<a href="https://colab.research.google.com/github/Eizer-GH/PDS/blob/main/Ex3_B4_55_PrasadV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

```
NAME - Prasad Sanjay Vangujare
CLASS - SY.B [AIDS]
ROLL NO.- B55
SUBJECT - EX_3 PDS
```

```
AIM - Data Wrangling with pandas: Manipulate and transform data to suit the analysis needs
```

```
Theory :

Q1. What is data wrangling, and why is it important before analysis?
Answer:
Data wrangling is the process of cleaning, transforming, and organizing raw data into
a structured format suitable for analysis. It includes handling missing values,
correcting errors, removing duplicates, and converting data types.

Data wrangling is important before analysis because raw data is often incomplete,
inconsistent, or incorrectly formatted. Cleaning the data ensures accuracy, improves
data quality, and helps produce reliable results during analysis and visualization.


Q2. You receive messy data with missing values, duplicates, and wrong types.
What steps will you follow to clean it?
Answer:
The following steps can be followed to clean messy data in a systematic and efficient
manner before starting any form of analysis.

1. Load the dataset using pandas so that the data becomes available for inspection
   and further processing.
2. Check the structure of the dataset using functions like head(), info(), and
   describe() to understand the layout and condition of the data.
3. Identify missing values using isnull() or notnull() to locate incomplete entries.
4. Handle missing values by removing unnecessary rows or columns, or filling them
   with suitable values using fillna().
5. Identify duplicate rows using duplicated() and remove them using
   drop_duplicates() to avoid repeated records.
6. Check data types using dtypes and convert incorrect types using astype()
   so that calculations can be performed correctly.
7. Rename incorrect or unclear column names if required to improve readability
   and understanding of the dataset.
8. Detect and handle outliers if necessary to prevent extreme values from affecting
   the analysis results.
9. Verify the cleaned dataset carefully before performing further analysis.


Q3. How can you check column names, data types, and summary statistics?
What does info() show that describe() does not?
Answer:
Column names can be checked using df.columns to display all available column labels.
Data types can be checked using df.dtypes to understand the format of stored values.
Summary statistics can be checked using df.describe() to view statistical measures.

The info() function provides details about column names, number of non-null values,
data types of each column, and memory usage of the dataset, which helps understand
the structure of the data.

The describe() function provides statistical summaries such as mean, median,
standard deviation, minimum and maximum values, and percentiles, which help in
understanding the distribution of numerical data.

The info() function shows non-null counts and memory usage, which describe() does
not provide, making it useful for checking missing data and memory optimization.


Q4. How do you identify missing values and outliers in a dataset?
Answer:
Missing values can be identified using df.isnull() and df.isnull().sum(), which help
detect and count missing entries in each column of the dataset.

Outliers can be identified using summary statistics from describe(), visualization
methods such as box plots and scatter plots, identifying values that are far from
the average, and statistical methods like Interquartile Range (IQR) or Z-score.

Outliers are values that are significantly higher or lower than the rest of the
data and may affect the accuracy of analysis if not handled properly.


Q5. How do you reduce memory usage in pandas DataFrames?
Answer:
Memory usage in pandas DataFrames can be reduced by converting data types to smaller
types such as using int32 instead of int64, which reduces the amount of storage used
by numerical values.

Another useful method is converting object data types to category when possible,
as categorical data requires less memory compared to object data types.

Removing unnecessary columns that are not needed for analysis also helps reduce
memory usage and improves processing speed.

Using efficient file formats or compressed formats while saving data helps reduce
storage size, and checking memory usage using df.memory_usage() helps identify
large columns that need optimization.
```

In [ ]:
import pandas as pd

# Load dataset
df = pd.read_csv("cleaned_employee_data.csv")

# Display first few rows
df.head()

,Employee_ID,Name,Age,Gender,Department,Join_Date,Salary,Experience,Performance_Rating,Bonus,Work_Hours_Per_Week
0,101,Alice,50,Female,Marketing,2009-01-18,62606,13,2,9488,44
1,102,Bob,36,Female,Marketing,2012-01-01,41534,1,1,5206,40
2,103,Charlie,29,Female,IT,2007-02-15,76338,9,4,10134,33
3,104,David,42,Male,Marketing,2015-12-29,31016,7,1,10977,42
4,105,Eve,40,Female,IT,2005-02-04,119789,9,4,12721,36

In [ ]:
# Select single column (Salary)
salary_column = df["Salary"]

salary_column.head()

0     62606
1     41534
2     76338
3     31016
4    119789
Name: Salary, dtype: int64

In [ ]:
# Add new column with constant value
df["Company_Name"] = "ABC_Corp"
df.iloc[:, :7].head()
df.iloc[:, 7:].head()

   Experience  Performance_Rating  Bonus  Work_Hours_Per_Week Company_Name
0          13                   2   9488                   44     ABC_Corp
1           1                   1   5206                   40     ABC_Corp
2           9                   4  10134                   33     ABC_Corp
3           7                   1  10977                   42     ABC_Corp
4           9                   4  12721                   36     ABC_Corp

In [ ]:
# Sort DataFrame by Age
sorted_df = df.sort_values(by="Age")

sorted_df.iloc[:, :4].head()

    Employee_ID     Name  Age  Gender
13          114     Nina   23  Female
17          118     Rose   23  Female
11          112      Leo   24  Female
2           103  Charlie   29  Female
6           107    Grace   32    Male

In [ ]:
# Rename column
df = df.rename(columns={
    "Work_Hours_Per_Week": "Weekly_Hours"
})

df.head()

,Employee_ID,Name,Age,Gender,Department,Join_Date,Salary,Experience,Performance_Rating,Bonus,Weekly_Hours,Company_Name
0,101,Alice,50,Female,Marketing,2009-01-18,62606,13,2,9488,44,ABC_Corp
1,102,Bob,36,Female,Marketing,2012-01-01,41534,1,1,5206,40,ABC_Corp
2,103,Charlie,29,Female,IT,2007-02-15,76338,9,4,10134,33,ABC_Corp
3,104,David,42,Male,Marketing,2015-12-29,31016,7,1,10977,42,ABC_Corp
4,105,Eve,40,Female,IT,2005-02-04,119789,9,4,12721,36,ABC_Corp

In [ ]:
# Summary statistics
df.describe()

,Employee_ID,Age,Salary,Experience,Performance_Rating,Bonus,Weekly_Hours
count,20.00000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000
mean,110.50000,40.800000,76338.350000,6.500000,2.750000,11033.400000,39.150000
std,5.91608,10.909195,30882.861701,4.006574,1.409554,3637.981632,5.760802
min,101.00000,23.000000,31016.000000,1.000000,1.000000,5206.000000,30.000000
25%,105.75000,32.000000,50481.500000,3.000000,1.750000,9063.500000,35.750000
50%,110.50000,42.500000,72718.500000,7.500000,3.000000,11203.500000,39.500000
75%,115.25000,46.250000,106248.250000,9.250000,4.000000,12610.750000,42.000000
max,120.00000,59.000000,119812.000000,13.000000,5.000000,19820.000000,49.000000

In [ ]:
# Filter employees with Salary > 70000 and Experience < 7
filtered_df = df[
    (df["Salary"] > 70000) &
    (df["Experience"] < 7)
]

filtered_df.iloc[:, :8].head()

    Employee_ID   Name  Age  Gender Department   Join_Date  Salary  Experience
5           106  Frank   44    Male  Marketing  2013-08-19   85591           6
6           107  Grace   32    Male  Marketing  2010-05-10  119812           1
12          113   Mona   43  Female         HR  2012-02-27  116807           1
14          115  Oscar   45  Female         HR  2015-07-11   93704           3
15          116   Paul   51    Male         IT  2009-02-09  116779           3

In [ ]:
# Group by Department and calculate mean Salary
grouped_df = df.groupby("Department")["Salary"].mean()

grouped_df

Department
HR           83772.833333
IT           71184.571429
Marketing    75119.714286
Name: Salary, dtype: float64

In [ ]:
# Create small second DataFrame
dept_info = pd.DataFrame({
    "Department": ["HR", "Marketing", "IT"],
    "Location": ["Delhi", "Mumbai", "Pune"]
})

# Merge with original DataFrame
merged_df = pd.merge(df, dept_info, on="Department")

merged_df.iloc[:, 4:][5:13]

,Department,Join_Date,Salary,Experience,Performance_Rating,Bonus,Weekly_Hours,Company_Name,Location
5,Marketing,2013-08-19,85591,6,2,12035,48,ABC_Corp,Mumbai
6,Marketing,2010-05-10,119812,1,1,6484,31,ABC_Corp,Mumbai
7,IT,2009-05-05,53247,12,5,12858,39,ABC_Corp,Pune
8,IT,2015-10-19,54300,8,2,5863,42,ABC_Corp,Pune
9,Marketing,2013-06-01,104065,8,4,7790,35,ABC_Corp,Mumbai
10,HR,2007-10-19,112798,11,3,12408,41,ABC_Corp,Delhi
11,IT,2014-06-24,39268,3,3,13755,41,ABC_Corp,Pune
12,HR,2012-02-27,116807,1,1,10116,49,ABC_Corp,Delhi

In [ ]:
# Drop columns
df_dropped = df.drop(columns=["Company_Name","Performance_Rating"])

# Drop rows with index 0 and 1
df_dropped = df_dropped.drop(index=[0, 1])

df_dropped.head()

,Employee_ID,Name,Age,Gender,Department,Join_Date,Salary,Experience,Bonus,Weekly_Hours
2,103,Charlie,29,Female,IT,2007-02-15,76338,9,10134,33
3,104,David,42,Male,Marketing,2015-12-29,31016,7,10977,42
4,105,Eve,40,Female,IT,2005-02-04,119789,9,12721,36
5,106,Frank,44,Male,Marketing,2013-08-19,85591,6,12035,48
6,107,Grace,32,Male,Marketing,2010-05-10,119812,1,6484,31

In [ ]:
# Increase bonus by 10%

def increase_Bonus(x):
    return x * 1.10

df["Updated_Bonus"] = df["Bonus"].apply(increase_Bonus)

df.iloc[:, 9:].head()

   Bonus  Weekly_Hours Company_Name  Updated_Bonus
0   9488            44     ABC_Corp        10436.8
1   5206            40     ABC_Corp         5726.6
2  10134            33     ABC_Corp        11147.4
3  10977            42     ABC_Corp        12074.7
4  12721            36     ABC_Corp        13993.1

In [ ]:
# Task 11A: Pivot Operation

pivot_table = df.pivot_table(
    values="Age",
    index="Department",
    aggfunc="mean"
)

pivot_table

                  Age
Department
HR          42.833333
IT          34.857143
Marketing   45.000000

In [ ]:
# Task 11B: Melt Operation

melted_df = pd.melt(
    df,
    id_vars=["Employee_ID", "Department"],
    value_vars=["Salary", "Bonus"],
    var_name="Pay_Type",
    value_name="Amount"
)

melted_df.head()

   Employee_ID Department Pay_Type  Amount
0          101  Marketing   Salary   62606
1          102  Marketing   Salary   41534
2          103         IT   Salary   76338
3          104  Marketing   Salary   31016
4          105         IT   Salary  119789

```
Conclusion :

In this practical, data wrangling techniques were performed using the pandas library
to manipulate and transform data into a suitable format for analysis. Various basic
operations such as selecting columns, adding new columns, sorting data, renaming
columns, and generating summary statistics were successfully carried out.

Further, moderate-level operations including filtering rows with multiple conditions,
grouping data based on categorical columns, merging DataFrames, dropping unwanted
rows and columns, and applying functions to columns were implemented effectively.

Advanced reshaping techniques such as pivot and melt operations were also performed
to understand how data can be reorganized between wide and long formats. Overall,
this practical helped in understanding how pandas can be used efficiently to clean,
organize, and transform datasets for meaningful analysis and better decision making.
```

In [ ]:
df.to_csv("Wrangled_employee_data.csv", index=False)